config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :recipes, only: %i[show index]

  root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
# Value Object
class Recipe
  attr_reader :id, :title, :image, :tags, :description, :chef_name

  def initialize(id:, title:, image:, tags: nil, description: nil, chef_name: nil)
    @id, @title, @image, @tags, @description, @chef_name = id, title, image, tags, description, chef_name
  end

  def self.all
    ContentDelivery::ListRecipes.new.call
  end

  def self.find(id)
    ContentDelivery::ShowRecipe.new.call(id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    if @recipe.nil?
      flash[:error] = "Recipe not found"
      redirect_to :recipes
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def styled_description(text)
    text = decorate(text)
    text = handle_links(text)
    text.html_safe
  end

  def decorate(text)
    text = text.gsub(/\*(.*)\*/, "<b>\\1</b>")
    text = text.gsub(/__([^\_]*)__/, "<i>\\1</i>")
  end

  def handle_links(text)
    text = text.gsub(/\[(.*)\]\((.*)\)/, "<a href='\\2' target='_blank'>\\1</a>")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MySpoon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="pb-5">
      <div class="container">
        <% flash.each do |type, msg| %>
          <div class="alert alert-danger" role="alert">
            <%= msg %>
          </div>
        <% end %>
        
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>My Spoon</h1>
<div class=card-deck>
  <% if @recipes.present? %>
    <% @recipes.each do |recipe| %>
      <div class="card" style="width: 18rem;">
        <img src="<%= recipe.image[:url] %>" class="card-img-top" alt="<%= recipe.image[:title] %>">
        <div class="card-body">
          <h5 class="card-title"><%= recipe.title %></h5>
          <%= link_to "Show", recipe_path(recipe.id), class: "btn btn-primary"%>
        </div>
      </div>
    <% end %>
  <% else %>
    <div> No Recipes Found</div>
  <% end %>
</div>
  

app/views/recipes/show.html.erb
<div class="card">
  <div class="card-horizontal">
    <div class="img-square-wrapper">
      <img width='500rem;' src="<%= @recipe.image[:url] %>" alt="<%= @recipe.image[:title] %>">
    </div>
    <div class="card-body">
      <h5 class="card-title"><%= @recipe.title %></h5>
      <p class="card-text"><%= styled_description(@recipe.description) %></p>
      <% if @recipe.tags.present? %>
        <p class="card-text">Tags : 
          <% @recipe.tags.each do |tag| %>
            <span class="badge badge-info"><%= tag %></span>
          <% end %>
        </p>
      <% end %>
      <% if @recipe.chef_name.present? %>
        <p class="card-text">Chef : <b><%= @recipe.chef_name %></b></p>
      <% end %>
    </div>
  </div>
</div>

<%= link_to 'Back', recipes_path %>